# Generated by Django 4.2 on 2025-01-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applight', '0002_alter_about_title_alter_banner_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='icon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
